DEF[PORTVERSION]=	1.18.0
# ------------------------------------------------------------------------

NAMEBASE=		python-pygit2
VERSION=		${PORTVERSION}
KEYWORDS=		python
VARIANTS=		v12 v13
SDESC[v12]=		Python bindings for libgit2 (3.12)
SDESC[v13]=		Python bindings for libgit2 (3.13)
HOMEPAGE=		https://github.com/libgit2/pygit2
CONTACT=		Python_Automaton[python@ironwolf.systems]

DOWNLOAD_GROUPS=	main
SITES[main]=		PYPI/p/pygit2
DISTFILE[1]=		pygit2-${PORTVERSION}.tar.gz:main
DIST_SUBDIR=		python-src

SPKGS[v12]=		single
SPKGS[v13]=		single

OPTIONS_AVAILABLE=	PY312 PY313
OPTIONS_STANDARD=	none
VOPTS[v12]=		PY312=ON PY313=OFF
VOPTS[v13]=		PY312=OFF PY313=ON

# License listed at PyPI
# GPLv2 with linking exception

GENERATED=		yes
DISTNAME=		pygit2-${PORTVERSION}

# Requires-Dist extracted from pyproject.toml file


[PY312].USES_ON=			python:v12,pep517
[PY313].USES_ON=			python:v13,pep517

BUILD_DEPENDS=		libgit2:dev:std
BUILDRUN_DEPENDS=	libgit2:primary:std
			python-cffi:single:python_used
MAKE_ENV=		LIBGIT2={{LOCALBASE}}

post-patch:
	# This version check is always too conservative, causing breakage
	${REINPLACE_CMD} -e '/#error You need a compatible libgit2/d' \
		${WRKSRC}/src/types.h
